export const CHECK_JWT_TOKEN = 'CHECK_JWT_TOKEN';

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const GET_PROFILE_BY_USER_ID = 'GET_PROFILE_BY_USER_ID';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_LOADING_OFF = 'PROFILE_LOADING_OFF';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const ADD_PROFILE_EXPERIENCE = 'ADD_PROFILE_EXPERIENCE';
export const DELETE_PROFILE_EXPERIENCE = 'DELETE_PROFILE_EXPERIENCE';
export const ADD_PROFILE_EDUCATION = 'ADD_PROFILE_EDUCATION';
export const DELETE_PROFILE_EDUCATION = 'DELETE_PROFILE_EDUCATION';

export const GET_POST = 'GET_POST';
export const POST_NEW_POST = 'POST_NEW_POST';
export const GET_POSTS = 'GET_POSTS';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_LIKE = 'ADD_LIKE';
export const DELETE_POST_BY_ID = 'DELETE_POST_BY_ID';
export const POST_LOADING = 'POSTS_LOADING';
export const ADD_POST = 'ADD_POST';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';

export const CLEAR_ERROR = 'CLEAR_ERROR';
